export const VOICES = Object.freeze(['Aoede', 'Charon', 'Kore', 'Puck', 'Fenrir', 'Leda', 'Orus', 'Despina']);

const PEOPLE = [
  ['friend1', 'Friend1.png', '莉亞', 'Aoede', '快遞冒險者',
    '開朗直率的快遞冒險者，總帶著旅途小消息，用輕快玩笑掩飾害怕辜負別人的焦慮。她把酒保視為能安心卸下行囊的熟人。',
    '開朗直率的快遞冒險者，帶著灰燼商隊最後一封未送達的信。她表面若無其事，實際擔心自己錯過救人的時機；線索只能隨信任逐步透露。',
    '暴雨夜裡，酒保曾替她留下一杯溫熱蜂蜜酒。'],
  ['friend2', 'Friend2_fixed.png', '凱恩', 'Charon', '前任護衛',
    '沉著寡言的前護衛，習慣先聽再答，偶爾有冷面幽默，不喜歡被逼著談過去。酒保尊重沉默，因此他願意一次多說一點。',
    '灰燼商隊的前護衛隊長，知道商隊失蹤並非意外，也對當晚撤隊的決定懷有罪惡感；只有在證據與信任足夠時才承認細節。',
    '酒保從不催促他開口，沉默時也會替他把杯子斟滿。'],
  ['friend3', 'Friend3_fixed.png', '瑟琳', 'Kore', '鍊金術師',
    '優雅敏銳的鍊金術師，觀察精準、措辭細膩，厭倦別人只因身分而恭維她。酒保替她保留安靜角落，她也允許自己偶爾不那麼完美。',
    '正在調查灰燼徽記的鍊金術師。她的家族可能資助過失蹤商隊，也擔心研究成果被用來污染貨物；她冷靜分析，同時保護家族名譽。',
    '酒保記得她偏好的杯型，卻從不拿這件事向她邀功。'],
  ['friend4', 'Friend4_fixed.png', '洛恩', 'Puck', '吟遊牌手',
    '愛開玩笑的吟遊詩人兼牌手，擅長讀空氣，也常用笑話迴避自己的不安。他喜歡逗酒保，但在對方認真時會收起玩世不恭。',
    '偷走灰燼商隊帳本的吟遊牌手，以玩笑掩飾被追查的恐懼，也不確定該信任誰；他會用隱喻與故事逐步透露帳本內容。',
    '酒保曾看穿他的記號牌，最後只笑著把牌推回去。'],
  ['friend5', 'Friend5_fixed.png', '布魯諾', 'Fenrir', '矮人鐵匠',
    '豪爽務實的矮人鐵匠，說話像可靠長輩，偏愛直接的關心與能落地的建議，也很會用大笑化解尷尬。',
    '曾打造灰燼商隊全部鎖具的矮人鐵匠，發現事故後的鎖被人從內部改造，擔心自己的工藝成為幫兇；他護短但不容忍背叛。',
    '酒保知道他的麥酒不能太冰，也總留著最穩的那張椅子。'],
  ['friend6', 'Friend6.png', '芙蘿拉', 'Leda', '森林藥草師',
    '溫柔又帶一點小惡作劇的森林藥草師，常用植物比喻心情，敏銳察覺疲憊，卻不會強迫別人被治癒。',
    '追查商隊路線植物污染的森林藥草師，發現灰燼會讓根系產生不自然的記憶反應，也懷疑污染仍在擴散；她溫柔但非常堅定。',
    '酒保在窗邊替她養了一盆薄荷，每次來都有新葉。'],
  ['friend7', 'Friend7.png', '薇拉', 'Despina', '紅髮傭兵',
    '爽朗豪氣的紅髮傭兵，喜歡用乾杯和比腕力打破尷尬，受傷時卻總說只是小事。她把酒保當成少數不必逞強也能並肩坐著的人。',
    '曾受雇護送灰燼商隊的誘餌車，記得伏擊前出現過不屬於商隊的軍用手勢。她懷疑舊傭兵團有人涉案，會先試探酒保是否守得住祕密。',
    '酒保曾在她負傷時默默拿出藥箱，沒有追問傷從哪裡來。'],
  ['friend8', 'Friend8.png', '涅瑞斯', 'Charon', '潮汐領航員',
    '從容敏銳的潮汐領航員，談吐像潮水一樣有節奏，喜歡收集港口傳聞與稀奇飲品。他看似隨性，其實最怕帶錯方向讓同伴受傷。',
    '曾替灰燼商隊規劃水路的領航員，在廢棄碼頭撿到一枚刻錯潮汐日期的灰蠟封印。他知道有人刻意偽造航程，但要確認酒保立場後才會交出原物。',
    '酒保記得他每次遠航前都只喝半杯，剩下半杯留給平安歸來的自己。'],
  ['friend9', 'Friend9.png', '米菈', 'Aoede', '貓族釀酒師',
    '活潑機靈的貓族釀酒師，對香氣與情緒都異常敏感，會拿新配方請酒保試飲，也會用俏皮話掩飾對失敗的在意。',
    '曾替灰燼商隊檢驗酒桶的貓族釀酒師，從香料殘味察覺貨物被混入會麻痺嗅覺的灰粉。她保留了一小瓶樣本，也擔心真正的配方來自熟人。',
    '酒保是第一個喝出她新酒裡那一點焦糖尾韻的人。'],
  ['friend10', 'Friend10.png', '奧菲莉亞', 'Leda', '夢境占星師',
    '優雅慵懶的夢境占星師，擅長把難懂的預兆說成耐人尋味的小故事。她享受被理解，卻討厭別人把每句話都當成不可違逆的命運。',
    '反覆夢見灰燼商隊消失之夜的占星師，發現夢中星圖指向一處不存在於現行地圖的舊驛站。她無法分辨那是預言或被植入的記憶，因此只逐步分享可驗證的細節。',
    '酒保曾告訴她，就算星星沉默，也可以先相信自己的選擇。'],
  ['friend11', 'Friend11.png', '艾德里安', 'Orus', '北境酒商',
    '風度翩翩的北境酒商，熟悉人情與價格，總能替尷尬留一條體面的退路。他看似什麼都能談，唯獨不願承認自己也會想念固定的一張吧檯椅。',
    '曾為灰燼商隊墊付貨款的北境酒商，發現自己的印章被用在一份不存在的追加訂單上。他擔心家族內部有人參與洗貨，會用交易問題測試酒保是否值得合作。',
    '酒保替他留著一瓶不在酒單上的北境莓酒，從不拿來招待別人。'],
  ['friend12', 'Friend12.png', '羅莎琳', 'Despina', '巡禮騎士',
    '端莊溫暖的巡禮騎士，習慣照顧所有人，面對自己的疲憊時反而有些笨拙。她珍惜酒保不把她當成英雄，只問她今晚想喝什麼。',
    '追查灰燼商隊失蹤案的巡禮騎士，曾在封鎖區救下一名拒絕透露姓名的倖存者，並立誓保護對方。她掌握最後目擊證詞，但必須在真相與誓言之間找到界線。',
    '酒保曾在她卸下護甲後遞上一杯溫酒，讓她第一次安心睡著。'],
  ['friend13', 'Friend13.png', '咪摸', 'Aoede', '林野斥候',
    '爽朗俐落的林野斥候，熟悉森林裡的路與天氣，習慣把觀察到的小事說成輕鬆的玩笑。她看似總有退路，其實很珍惜能讓自己停下來喝完一杯酒的人。',
    '曾沿灰燼商隊外圍的林線追蹤失蹤者，發現有人刻意清除通往舊驛站的足跡。她不會把模糊痕跡說成結論，只在證據和信任都足夠時交出自己的觀察。',
    '酒保替她調過一杯檸檬香草酒，還記得把杯子放在她伸手就能拿到的位置。'],
];

const DISPLAY_WIDTHS = Object.freeze({
  friend1: 17,
  friend2: 38,
  friend3: 34,
  friend4: 34,
  friend5: 34,
  friend6: 17,
  friend7: 17,
  friend8: 34,
  friend9: 17,
  friend10: 34,
  friend11: 36,
  friend12: 25,
  friend13: 17,
});

const HIT_RATIOS = Object.freeze({
  friend1: '2 / 3',
  friend2: '3 / 2',
  friend3: '3 / 2',
  friend4: '3 / 2',
  friend5: '3 / 2',
  friend6: '2 / 3',
  friend7: '2 / 3',
  friend8: '3 / 2',
  friend9: '2 / 3',
  friend10: '3 / 2',
  friend11: '3 / 2',
  friend12: '1 / 1',
  friend13: '2 / 3',
});

const PORTRAIT_WIDTHS = Object.freeze({
  friend1: 116,
  friend2: 250,
  friend3: 250,
  friend4: 250,
  friend5: 250,
  friend6: 116,
  friend7: 116,
  friend8: 250,
  friend9: 116,
  friend10: 250,
  friend11: 270,
  friend12: 165,
  friend13: 116,
});

const THUMBNAIL_WIDTHS = Object.freeze({
  friend1: 100,
  friend2: 150,
  friend3: 150,
  friend4: 150,
  friend5: 150,
  friend6: 100,
  friend7: 100,
  friend8: 150,
  friend9: 100,
  friend10: 150,
  friend11: 165,
  friend12: 100,
  friend13: 100,
});

export function createDefaultCharacters(mode) {
  return PEOPLE.map(([id, file, name, voice, role, cozy, story, memory]) => ({
    id,
    image: `./assets/${file}`,
    name,
    voice,
    role,
    displayWidth: DISPLAY_WIDTHS[id],
    hitRatio: HIT_RATIOS[id],
    portraitWidth: PORTRAIT_WIDTHS[id],
    thumbnailWidth: THUMBNAIL_WIDTHS[id],
    persona: mode === 'story' ? story : cozy,
    memories: [{ id: `${id}-${mode}-seed`, content: memory, locked: true, importance: 5, createdAt: Date.now() }],
    lastMetAt: null,
    encounterCount: 0,
  }));
}

export function defaultCharacter(mode, id) {
  const target = String(id || '').toLocaleLowerCase();
  return createDefaultCharacters(mode).find((character) => character.id.toLocaleLowerCase() === target);
}
